CREATE TABLE CLIENTES (
    ID_Cliente INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Telefone VARCHAR(15),
    Senha VARCHAR(255) NOT NULL
);

CREATE TABLE RESTAURANTES (
    ID_Restaurante INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Endereco VARCHAR(255) NOT NULL,
    Categoria VARCHAR(50),
    Avaliacao_Media DECIMAL(3, 2) DEFAULT 0
);

CREATE TABLE PRODUTOS (
    ID_Produto INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Descricao TEXT,
    Preco DECIMAL(10, 2) NOT NULL,
    ID_Restaurante INT,
    FOREIGN KEY (ID_Restaurante) REFERENCES RESTAURANTES(ID_Restaurante)
);

CREATE TABLE ENDERECOS_ENTREGA (
    ID_Endereco INT PRIMARY KEY AUTO_INCREMENT,
    ID_Cliente INT,
    Rua VARCHAR(100) NOT NULL,
    Numero VARCHAR(10) NOT NULL,
    Bairro VARCHAR(50),
    Cidade VARCHAR(50),
    Estado VARCHAR(2),
    CEP VARCHAR(10),
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTES(ID_Cliente)
);

CREATE TABLE FORMAS_PAGAMENTO (
    ID_Forma_Pagamento INT PRIMARY KEY AUTO_INCREMENT,
    Descricao VARCHAR(50) NOT NULL -- Ex: Cartão de Crédito, PIX, Dinheiro
);

CREATE TABLE PEDIDOS (
    ID_Pedido INT PRIMARY KEY AUTO_INCREMENT,
    ID_Cliente INT,
    Data_Hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_Endereco_Entrega INT,
    ID_Forma_Pagamento INT,
    Valor_Total DECIMAL(10, 2) NOT NULL,
    Status VARCHAR(50) DEFAULT 'Em preparo',
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTES(ID_Cliente),
    FOREIGN KEY (ID_Endereco_Entrega) REFERENCES ENDERECOS_ENTREGA(ID_Endereco),
    FOREIGN KEY (ID_Forma_Pagamento) REFERENCES FORMAS_PAGAMENTO(ID_Forma_Pagamento)
);

CREATE TABLE ITENS_PEDIDO (
    ID_Item INT PRIMARY KEY AUTO_INCREMENT,
    ID_Pedido INT,
    ID_Produto INT,
    Quantidade INT NOT NULL,
    Preco DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_Pedido) REFERENCES PEDIDOS(ID_Pedido),
    FOREIGN KEY (ID_Produto) REFERENCES PRODUTOS(ID_Produto)
);

CREATE TABLE AVALIACOES (
    ID_Avaliacao INT PRIMARY KEY AUTO_INCREMENT,
    ID_Restaurante INT,
    ID_Cliente INT,
    Nota INT CHECK (Nota BETWEEN 1 AND 5),
    Comentario TEXT,
    Data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_Restaurante) REFERENCES RESTAURANTES(ID_Restaurante),
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTES(ID_Cliente)
);

