CREATE TABLE AVALIACOES (
    ID_Avaliacao INT PRIMARY KEY AUTO_INCREMENT,
    ID_Restaurante INT,
    ID_Cliente INT,
    Nota INT CHECK (Nota BETWEEN 1 AND 5),
    Comentario TEXT,
    Data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_Restaurante) REFERENCES RESTAURANTES(ID_Restaurante),
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTES(ID_Cliente)
);
